# Generated by Django 5.2.5 on 2025-09-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
